import { describe, expect, it } from 'vitest'
import { types } from '../../../wailsjs/go/models'
import type { ContinuityDecision } from '../../types/draftline'
import {
  buildReviewCards,
  cardActions,
  continuitySignalIdFor,
  extractQuote,
  kindPriority,
  layoutReviewCards,
  loopContextId,
  reviewKindLabel,
  sha256Hex,
  stableDiagnosticId,
  withLoopContext,
  withoutCorrection,
} from './reviewDeskModel'

function diagnostic(partial: Partial<types.FingerprintDiagnostic> & { id: string; kind: string }): types.FingerprintDiagnostic {
  return types.FingerprintDiagnostic.createFrom({
    severity: 'review',
    title: partial.id,
    detail: '',
    confidence: 1,
    ...partial,
  })
}

function fingerprint(partial: {
  diagnostics?: types.FingerprintDiagnostic[]
  threads?: types.StoryThread[]
  author_model?: types.StoryAuthorModel
}) {
  return partial
}

describe('sha256Hex', () => {
  it('matches the NIST vectors', () => {
    expect(sha256Hex('')).toBe('e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855')
    expect(sha256Hex('abc')).toBe('ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad')
  })

  it('handles messages that cross the 64-byte block boundary', () => {
    // 56 bytes forces a second padding block.
    expect(sha256Hex('a'.repeat(56))).toBe(
      'b35439a4ac6f0948b6d6f9e3c6af0f5f590ce20f1bde7090ef7970686ec6738a',
    )
  })
})

describe('backend id derivations', () => {
  // Expected values generated by running the actual Go hashing code
  // (stableID / continuity signal()) with these inputs.
  it('mirrors fingerprint stableID for diagnostics', () => {
    expect(stableDiagnosticId('corr-1', 'orphaned')).toBe('diagnostic-fdee7b7345954169')
    expect(stableDiagnosticId('correction-ab12', 'orphaned')).toBe('diagnostic-4f9e997adca75d64')
  })

  it('mirrors the folded continuity signal id without sources', () => {
    const item = diagnostic({ id: 'x', kind: 'near_duplicate_chapter', title: 'Two chapters are nearly identical' })
    expect(continuitySignalIdFor(item)).toBe('continuity-11225d229b0631de')
  })

  it('mirrors the folded continuity signal id with resolvable sources', () => {
    const item = diagnostic({ id: 'x', kind: 'attribute_conflict', title: 'Eye color conflict', evidence_ids: ['ev-1', 'ev-2'] })
    const records = new Map([
      ['ev-1', { chapter_id: 'ch-a' }],
      ['ev-2', { chapter_id: 'ch-b' }],
    ])
    expect(continuitySignalIdFor(item, records)).toBe('continuity-8482720bc6d28cf2')
  })

  it('skips evidence ids that do not resolve to a record, like the backend does', () => {
    const item = diagnostic({ id: 'x', kind: 'near_duplicate_chapter', title: 'Two chapters are nearly identical', evidence_ids: ['missing'] })
    expect(continuitySignalIdFor(item, new Map())).toBe('continuity-11225d229b0631de')
  })
})

describe('buildReviewCards', () => {
  it('returns no cards without a fingerprint or diagnostics', () => {
    expect(buildReviewCards(undefined, [])).toEqual([])
    expect(buildReviewCards(fingerprint({ diagnostics: [] }), [])).toEqual([])
  })

  it('orders undecided cards by kind priority and sinks decided cards', () => {
    const cards = buildReviewCards(
      fingerprint({
        diagnostics: [
          diagnostic({ id: 'd-dormant', kind: 'dormant_thread' }),
          diagnostic({ id: 'd-canon', kind: 'canon_conflict' }),
          diagnostic({ id: 'd-dupe', kind: 'near_duplicate_chapter' }),
          diagnostic({ id: 'd-presence', kind: 'unclosed_presence' }),
        ],
      }),
      [{ signal_id: 'd-canon', status: 'dismissed' }],
    )
    expect(cards.map(card => card.id)).toEqual(['d-dupe', 'd-presence', 'd-dormant', 'd-canon'])
    expect(cards[3].decided).toBe('dismissed')
  })

  it('marks a card decided when the decision uses the folded continuity signal id', () => {
    const item = diagnostic({ id: 'd-1', kind: 'near_duplicate_chapter', title: 'Two chapters are nearly identical' })
    const decisions: ContinuityDecision[] = [{ signal_id: 'continuity-11225d229b0631de', status: 'reviewed' }]
    const cards = buildReviewCards(fingerprint({ diagnostics: [item] }), decisions)
    expect(cards[0].decided).toBe('reviewed')
    expect(cards[0].decisionIds).toEqual(['d-1', 'continuity-11225d229b0631de'])
  })

  it('shows confidence only below 95%', () => {
    const cards = buildReviewCards(
      fingerprint({
        diagnostics: [
          diagnostic({ id: 'a', kind: 'attribute_conflict', confidence: 0.94 }),
          diagnostic({ id: 'b', kind: 'attribute_conflict', confidence: 0.95 }),
        ],
      }),
      [],
    )
    expect(cards.find(card => card.id === 'a')?.confidencePct).toBe(94)
    expect(cards.find(card => card.id === 'b')?.confidencePct).toBeUndefined()
  })

  it('recovers the dormant chapter count from the matching thread', () => {
    const thread = types.StoryThread.createFrom({ id: 'thread-9', state: 'dormant', dormant_chapters: 6 })
    const item = diagnostic({ id: stableDiagnosticId('thread-9', 'dormant'), kind: 'dormant_thread' })
    const cards = buildReviewCards(fingerprint({ diagnostics: [item], threads: [thread] }), [])
    expect(cards[0].dormantChapters).toBe(6)
    expect(cards[0].kindLabel).toBe('DORMANT THREAD · 6 CHAPTERS')
  })

  it('falls back to parsing the dormant count from the detail text', () => {
    const item = diagnostic({
      id: 'd-x',
      kind: 'dormant_thread',
      detail: 'The promise has no matching evidence for 3 chapters. It may be intentionally deferred.',
    })
    const cards = buildReviewCards(fingerprint({ diagnostics: [item] }), [])
    expect(cards[0].kindLabel).toBe('DORMANT THREAD · 3 CHAPTERS')
  })

  it('links an orphaned_correction card to its author correction via the id hash', () => {
    const correction = types.FingerprintCorrection.createFrom({ id: 'corr-1', target_id: 'ev-9', kind: 'story_day', value: '4', status: 'orphaned' })
    const model = types.StoryAuthorModel.createFrom({ corrections: [correction] })
    const item = diagnostic({ id: 'diagnostic-fdee7b7345954169', kind: 'orphaned_correction' })
    const cards = buildReviewCards(fingerprint({ diagnostics: [item], author_model: model }), [])
    expect(cards[0].correctionId).toBe('corr-1')
  })

  it('extracts a quotable excerpt only for near-duplicate details that carry one', () => {
    const quoted = diagnostic({ id: 'a', kind: 'near_duplicate_chapter', detail: 'They both open with “STARTING SIMULATION: 144,334” and diverge after.' })
    const plain = diagnostic({ id: 'b', kind: 'near_duplicate_chapter', detail: 'Prologue and Epilogue share 98% of their normalized phrasing.' })
    const cards = buildReviewCards(fingerprint({ diagnostics: [quoted, plain] }), [])
    expect(cards.find(card => card.id === 'a')?.excerpt).toBe('STARTING SIMULATION: 144,334')
    expect(cards.find(card => card.id === 'b')?.excerpt).toBeUndefined()
  })
})

describe('labels and priorities', () => {
  it('maps every diagnostic kind to its human label', () => {
    expect(reviewKindLabel('near_duplicate_chapter')).toBe('TEMPORAL ANOMALY · NEEDS A CALL')
    expect(reviewKindLabel('unclosed_presence')).toBe('UNRESOLVED PRESENCE')
    expect(reviewKindLabel('attribute_conflict')).toBe('ATTRIBUTE CONFLICT')
    expect(reviewKindLabel('direction_conflict')).toBe('DIRECTIONAL CONFLICT')
    expect(reviewKindLabel('canon_conflict')).toBe('CANON VIOLATION')
    expect(reviewKindLabel('identity_conflict')).toBe('IDENTITY CONFLICT')
    expect(reviewKindLabel('orphan_character')).toBe('FORGOTTEN INTRODUCTION')
    expect(reviewKindLabel('orphaned_correction')).toBe('ORPHANED CORRECTION')
    expect(reviewKindLabel('checkpoint_too_early')).toBe('CHECKPOINT TOO EARLY')
    expect(reviewKindLabel('dormant_thread', 1)).toBe('DORMANT THREAD · 1 CHAPTER')
    expect(reviewKindLabel('some_new_kind')).toBe('SOME NEW KIND')
  })

  it('ranks kinds in the documented order', () => {
    const order = [
      'near_duplicate_chapter',
      'canon_conflict',
      'unclosed_presence',
      'direction_conflict',
      'attribute_conflict',
      'identity_conflict',
      'orphaned_correction',
      'checkpoint_too_early',
      'orphan_character',
      'dormant_thread',
    ]
    for (let index = 1; index < order.length; index++) {
      expect(kindPriority(order[index - 1])).toBeLessThan(kindPriority(order[index]))
    }
    expect(kindPriority('unknown')).toBeGreaterThan(kindPriority('dormant_thread'))
  })
})

describe('cardActions', () => {
  const base = (kind: string, extra: Record<string, unknown> = {}) =>
    buildReviewCards(fingerprint({ diagnostics: [diagnostic({ id: 'd', kind, ...extra })] }), [])[0]

  it('offers reset/flag for near-duplicates', () => {
    expect(cardActions(base('near_duplicate_chapter')).map(action => action.action)).toEqual(['reset', 'flag_duplicate'])
  })

  it('offers thread navigation for dormant threads', () => {
    expect(cardActions(base('dormant_thread')).map(action => action.action)).toEqual(['open_threads', 'intentional'])
  })

  it('offers a disabled reattach plus discard for linked orphaned corrections', () => {
    const correction = types.FingerprintCorrection.createFrom({ id: 'corr-1', target_id: 't', kind: 'context', value: 'x', status: 'orphaned' })
    const model = types.StoryAuthorModel.createFrom({ corrections: [correction] })
    const item = diagnostic({ id: 'diagnostic-fdee7b7345954169', kind: 'orphaned_correction' })
    const card = buildReviewCards(fingerprint({ diagnostics: [item], author_model: model }), [])[0]
    const actions = cardActions(card)
    expect(actions[0]).toMatchObject({ action: 'reattach', disabled: true })
    expect(actions[1].action).toBe('discard_correction')
  })

  it('falls back to a plain dismissal when no correction matches the diagnostic', () => {
    const card = base('orphaned_correction')
    expect(cardActions(card)[1].action).toBe('dismiss')
  })

  it('uses the generic trio elsewhere and offers only reopen once decided', () => {
    const card = base('attribute_conflict', { evidence_ids: ['ev-1'] })
    expect(cardActions(card).map(action => action.action)).toEqual(['goto', 'review', 'dismiss'])
    expect(cardActions({ ...card, decided: 'reviewed' }).map(action => action.action)).toEqual(['reopen'])
  })
})

describe('layoutReviewCards', () => {
  it('promotes the top undecided card and splits the rest across two columns', () => {
    const cards = buildReviewCards(
      fingerprint({
        diagnostics: [
          diagnostic({ id: 'a', kind: 'near_duplicate_chapter' }),
          diagnostic({ id: 'b', kind: 'canon_conflict' }),
          diagnostic({ id: 'c', kind: 'attribute_conflict' }),
          diagnostic({ id: 'd', kind: 'dormant_thread' }),
        ],
      }),
      [{ signal_id: 'd', status: 'dismissed' }],
    )
    const layout = layoutReviewCards(cards)
    expect(layout.hero?.id).toBe('a')
    expect(layout.columns[0].map(card => card.id)).toEqual(['b', 'd'])
    expect(layout.columns[1].map(card => card.id)).toEqual(['c'])
    // Decided cards end up after undecided ones in their column.
    expect(layout.columns[0][1].decided).toBe('dismissed')
  })

  it('has no hero when every card is decided', () => {
    const cards = buildReviewCards(
      fingerprint({ diagnostics: [diagnostic({ id: 'a', kind: 'canon_conflict' })] }),
      [{ signal_id: 'a', status: 'reviewed' }],
    )
    expect(layoutReviewCards(cards).hero).toBeNull()
  })
})

describe('author-model drafts', () => {
  it('appends one simulation context per diagnostic, idempotently', () => {
    const first = withLoopContext(undefined, 'diagnostic-abc123')
    expect(first.added).toBe(true)
    expect(first.contextId).toBe(loopContextId('diagnostic-abc123'))
    expect(first.model.contexts).toHaveLength(1)
    expect(first.model.contexts[0]).toMatchObject({
      id: 'context-loop-abc123',
      kind: 'simulation',
      label: 'Loop iteration',
      source: 'author',
    })

    const again = withLoopContext(first.model, 'diagnostic-abc123')
    expect(again.added).toBe(false)
    expect(again.model.contexts).toHaveLength(1)
  })

  it('removes exactly the discarded correction and keeps the rest', () => {
    const keep = types.FingerprintCorrection.createFrom({ id: 'corr-keep', target_id: 't', kind: 'summary', value: 'v', status: 'active' })
    const drop = types.FingerprintCorrection.createFrom({ id: 'corr-drop', target_id: 't', kind: 'summary', value: 'v', status: 'orphaned' })
    const model = types.StoryAuthorModel.createFrom({ corrections: [keep, drop] })
    const result = withoutCorrection(model, 'corr-drop')
    expect(result.removed).toBe(true)
    expect(result.model.corrections.map(correction => correction.id)).toEqual(['corr-keep'])
    // The input model is untouched.
    expect(model.corrections).toHaveLength(2)
  })

  it('reports when nothing was removed', () => {
    expect(withoutCorrection(undefined, 'corr-x').removed).toBe(false)
  })
})

describe('extractQuote', () => {
  it('requires a minimum quotable length', () => {
    expect(extractQuote('He said “hi” and left.')).toBeUndefined()
    expect(extractQuote('It opens with "a long enough quoted passage" twice.')).toBe('a long enough quoted passage')
  })
})
