// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowseForDirectory():Promise<string>;

export function CancelRewrite():Promise<void>;

export function CheckClaudeCode():Promise<main.ClaudeCodeStatus>;

export function GetCurrentFile():Promise<string>;

export function LoadSettings():Promise<main.AppSettings>;

export function NewBook():Promise<main.BookData>;

export function OpenBookDialog():Promise<main.BookData>;

export function OpenClaudeAuth():Promise<void>;

export function RewriteText(arg1:string,arg2:string):Promise<main.AIRewriteResult>;

export function SaveBook(arg1:main.BookData):Promise<main.SaveResult>;

export function SaveBookAs(arg1:main.BookData):Promise<main.SaveResult>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function SetupClaudeCode():Promise<main.ClaudeCodeStatus>;

export function TestLocalAI(arg1:string):Promise<main.AIRewriteResult>;
