// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentProject(arg1) {
  return window['go']['main']['App']['AddRecentProject'](arg1);
}

export function BrowseForDirectory() {
  return window['go']['main']['App']['BrowseForDirectory']();
}

export function CancelRewrite() {
  return window['go']['main']['App']['CancelRewrite']();
}

export function CheckClaudeCode() {
  return window['go']['main']['App']['CheckClaudeCode']();
}

export function ClearRecentProjects() {
  return window['go']['main']['App']['ClearRecentProjects']();
}

export function ExportDOCX(arg1, arg2) {
  return window['go']['main']['App']['ExportDOCX'](arg1, arg2);
}

export function ExportEPUB(arg1, arg2) {
  return window['go']['main']['App']['ExportEPUB'](arg1, arg2);
}

export function ExportPDF(arg1, arg2) {
  return window['go']['main']['App']['ExportPDF'](arg1, arg2);
}

export function ExportPrintPDF(arg1, arg2) {
  return window['go']['main']['App']['ExportPrintPDF'](arg1, arg2);
}

export function GenerateInlineContent(arg1) {
  return window['go']['main']['App']['GenerateInlineContent'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCurrentFile() {
  return window['go']['main']['App']['GetCurrentFile']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function ImportDOCX(arg1) {
  return window['go']['main']['App']['ImportDOCX'](arg1);
}

export function ImportDOCXDialog() {
  return window['go']['main']['App']['ImportDOCXDialog']();
}

export function ImportEPUB(arg1) {
  return window['go']['main']['App']['ImportEPUB'](arg1);
}

export function ImportEPUBDialog() {
  return window['go']['main']['App']['ImportEPUBDialog']();
}

export function IndexBook(arg1) {
  return window['go']['main']['App']['IndexBook'](arg1);
}

export function IndexChapter(arg1, arg2, arg3) {
  return window['go']['main']['App']['IndexChapter'](arg1, arg2, arg3);
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function NewBook() {
  return window['go']['main']['App']['NewBook']();
}

export function OpenBookDialog() {
  return window['go']['main']['App']['OpenBookDialog']();
}

export function OpenClaudeAuth() {
  return window['go']['main']['App']['OpenClaudeAuth']();
}

export function OpenRecentProject(arg1) {
  return window['go']['main']['App']['OpenRecentProject'](arg1);
}

export function RemoveRecentProject(arg1) {
  return window['go']['main']['App']['RemoveRecentProject'](arg1);
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function RewriteText(arg1, arg2, arg3) {
  return window['go']['main']['App']['RewriteText'](arg1, arg2, arg3);
}

export function RewriteTextCustom(arg1, arg2) {
  return window['go']['main']['App']['RewriteTextCustom'](arg1, arg2);
}

export function SaveBook(arg1) {
  return window['go']['main']['App']['SaveBook'](arg1);
}

export function SaveBookAs(arg1) {
  return window['go']['main']['App']['SaveBookAs'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetupClaudeCode() {
  return window['go']['main']['App']['SetupClaudeCode']();
}

export function TestLocalAI(arg1) {
  return window['go']['main']['App']['TestLocalAI'](arg1);
}
