// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRecentProject(arg1:main.RecentProject):Promise<void>;

export function BrowseForDirectory():Promise<string>;

export function CancelRewrite():Promise<void>;

export function CheckClaudeCode():Promise<main.ClaudeCodeStatus>;

export function ClearRecentProjects():Promise<void>;

export function ExportDOCX(arg1:main.BookData,arg2:main.ExportOptions):Promise<main.ExportResult>;

export function ExportEPUB(arg1:main.BookData,arg2:main.ExportOptions):Promise<main.ExportResult>;

export function ExportPDF(arg1:main.BookData,arg2:main.PDFOptions):Promise<main.ExportResult>;

export function ExportPrintPDF(arg1:main.BookData,arg2:main.PrintPDFOptions):Promise<main.ExportResult>;

export function GenerateInlineContent(arg1:main.InlineGenerateRequest):Promise<main.AIRewriteResult>;

export function GetAppVersion():Promise<string>;

export function GetCurrentFile():Promise<string>;

export function GetRecentProjects():Promise<Array<main.RecentProject>>;

export function ImportDOCX(arg1:string):Promise<main.ImportResult>;

export function ImportDOCXDialog():Promise<main.ImportResult>;

export function ImportEPUB(arg1:string):Promise<main.ImportResult>;

export function ImportEPUBDialog():Promise<main.ImportResult>;

export function IndexBook(arg1:main.BookData):Promise<main.IndexResult>;

export function IndexChapter(arg1:main.BookData,arg2:string,arg3:number):Promise<main.IndexResult>;

export function ListBackups():Promise<Array<main.BackupInfo>>;

export function LoadSettings():Promise<main.AppSettings>;

export function NewBook():Promise<main.BookData>;

export function OpenBookDialog():Promise<main.BookData>;

export function OpenClaudeAuth():Promise<void>;

export function OpenRecentProject(arg1:string):Promise<main.BookData>;

export function RemoveRecentProject(arg1:string):Promise<void>;

export function RestoreBackup(arg1:number):Promise<main.SaveResult>;

export function RewriteText(arg1:string,arg2:string,arg3:string):Promise<main.AIRewriteResult>;

export function RewriteTextCustom(arg1:string,arg2:string):Promise<main.AIRewriteResult>;

export function SaveBook(arg1:main.BookData):Promise<main.SaveResult>;

export function SaveBookAs(arg1:main.BookData):Promise<main.SaveResult>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function SetupClaudeCode():Promise<main.ClaudeCodeStatus>;

export function TestLocalAI(arg1:string):Promise<main.AIRewriteResult>;
