// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function AddRecentProject(arg1:types.RecentProject):Promise<void>;

export function BrowseForDirectory():Promise<string>;

export function CancelRewrite():Promise<void>;

export function CheckClaudeCode():Promise<types.ClaudeCodeStatus>;

export function ClearRecentProjects():Promise<void>;

export function ExportDOCX(arg1:types.BookData,arg2:types.ExportOptions):Promise<types.ExportResult>;

export function ExportEPUB(arg1:types.BookData,arg2:types.ExportOptions):Promise<types.ExportResult>;

export function ExportPDF(arg1:types.BookData,arg2:types.PDFOptions):Promise<types.ExportResult>;

export function ExportPrintPDF(arg1:types.BookData,arg2:types.PrintPDFOptions):Promise<types.ExportResult>;

export function GenerateInlineContent(arg1:types.InlineGenerateRequest):Promise<types.AIRewriteResult>;

export function GetAppVersion():Promise<string>;

export function GetCurrentFile():Promise<string>;

export function GetRecentProjects():Promise<Array<types.RecentProject>>;

export function ImportDOCX(arg1:string):Promise<types.ImportResult>;

export function ImportDOCXDialog():Promise<types.ImportResult>;

export function ImportEPUB(arg1:string):Promise<types.ImportResult>;

export function ImportEPUBDialog():Promise<types.ImportResult>;

export function IndexBook(arg1:types.BookData):Promise<types.IndexResult>;

export function IndexChapter(arg1:types.BookData,arg2:string,arg3:number):Promise<types.IndexResult>;

export function ListBackups():Promise<Array<types.BackupInfo>>;

export function LoadSettings():Promise<types.AppSettings>;

export function NewBook():Promise<types.BookData>;

export function OpenBookDialog():Promise<types.BookData>;

export function OpenClaudeAuth():Promise<void>;

export function OpenRecentProject(arg1:string):Promise<types.BookData>;

export function RemoveRecentProject(arg1:string):Promise<void>;

export function RestoreBackup(arg1:number):Promise<types.SaveResult>;

export function RewriteText(arg1:string,arg2:string,arg3:string):Promise<types.AIRewriteResult>;

export function RewriteTextCustom(arg1:string,arg2:string):Promise<types.AIRewriteResult>;

export function SaveBook(arg1:types.BookData):Promise<types.SaveResult>;

export function SaveBookAs(arg1:types.BookData):Promise<types.SaveResult>;

export function SaveSettings(arg1:types.AppSettings):Promise<void>;

export function SetupClaudeCode():Promise<types.ClaudeCodeStatus>;

export function TestLocalAI(arg1:string):Promise<types.AIRewriteResult>;
