// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForDirectory() {
  return window['go']['main']['App']['BrowseForDirectory']();
}

export function CancelRewrite() {
  return window['go']['main']['App']['CancelRewrite']();
}

export function CheckClaudeCode() {
  return window['go']['main']['App']['CheckClaudeCode']();
}

export function GetCurrentFile() {
  return window['go']['main']['App']['GetCurrentFile']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function NewBook() {
  return window['go']['main']['App']['NewBook']();
}

export function OpenBookDialog() {
  return window['go']['main']['App']['OpenBookDialog']();
}

export function OpenClaudeAuth() {
  return window['go']['main']['App']['OpenClaudeAuth']();
}

export function RewriteText(arg1, arg2) {
  return window['go']['main']['App']['RewriteText'](arg1, arg2);
}

export function SaveBook(arg1) {
  return window['go']['main']['App']['SaveBook'](arg1);
}

export function SaveBookAs(arg1) {
  return window['go']['main']['App']['SaveBookAs'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetupClaudeCode() {
  return window['go']['main']['App']['SetupClaudeCode']();
}

export function TestLocalAI(arg1) {
  return window['go']['main']['App']['TestLocalAI'](arg1);
}
